import React from "react";
import { BackgroundBeams } from "@/components/ui/background-beams";
import { TracingBeam } from "@/components/ui/tracing-beam";
import SkeletonTwo from "@/components/shared/ImagesCard";
import DateComponent from "./Dates"
import {one_png, two_png, three_png} from '@/public/assets/images'

export default function Component() {
    return (
        <div className="w-full rounded-md bg-blue_bg relative flex flex-col items-center justify-center antialiased" id={"About"}>
            <div className="absolute top-0 inset-x-0 h-100 bg-gradient-to-b from-black via-[#090b0f] to-transparent w-full"/>
            <TracingBeam>
                <div className="flex max-w-7xl mt-20 mx-auto p-4 justify-between max-sm:pl-10">
                    <div
                        className="max-w-7xl w-full flex flex-col lg:flex-row items-center justify-between gap-8 lg:gap-16">
                        <div className="w-full lg:w-2/3 space-y-6 md:pl-5">
                            <div className={"w-fit relative"}>
                                <h1 className={"text-2xl md:text-4xl lg:text-6xl font-semibold text-white mb-4"}>
                                    About the Conference
                                </h1>
                                <div className={"absolute inset-x-20 bottom-0 left-0 bg-gradient-to-r from-transparent via-purple-600 to-transparent h-[2px] w-3/4 blur-sm"}/>
                                <div className={"absolute inset-x-20 bottom-0 left-0 bg-gradient-to-r from-transparent via-purple-600 to-transparent h-px w-3/4"}/>
                                <div className={"absolute inset-x-60 bottom-0 left-0 bg-gradient-to-r from-transparent via-orange-500 to-transparent h-[5px] w-1/4 blur-sm"}/>
                                <div className={"absolute inset-x-60 bottom-0 left-0 bg-gradient-to-r from-transparent via-orange-500 to-transparent h-px w-1/4"}/>

                            </div>
                            <p className="text-md lg:text-lg text-gray-300 leading-relaxed">
                                In this era of big data, data analysis and management is emerging as a significant
                                research field with a vision to manage the data from an information perspective.
                                Recent, the data intelligence domain combines with the increasing efforts of
                                Artificial Intelligence, Machine Learning, Deep Learning and Cognitive science to study
                                and develop a deeper understanding of the information processing systems. Furthermore,
                                the new cognitive informatics tools, algorithms and methods that mimic the mechanisms
                                of the human brain will lead to an impending revolution in understating a large amount
                                of data generated by various smart applications.
                                This 6th International Conference on Data Intelligence and Cognitive Informatics
                                [ICDCI 2025] welcomes researchers, academicians, scholars, and industrialists across the
                                globe to join the international research initiative on data intelligence and cognitive
                                informatics towards investigating the evolving information processing systems, and for
                                the development of next-generation cognitive informatics and communication technologies.
                            </p>
                        </div>
                        <div className="w-full z-20 mt-0 ml-0 lg:w-1/2 md:ml-10">
                            <SkeletonTwo
                                img1={one_png}
                                img2={two_png}
                                img3={three_png}
                            />
                        </div>
                    </div>
                </div>

                <div className="flex max-w-7xl mt-20 mx-auto p-4 justify-between max-sm:pl-10">
                    <div
                        className="max-w-7xl w-full flex flex-col lg:flex-row items-center lg:items-start justify-between gap-8 lg:gap-16">
                        <div className="w-full lg:w-1/2 order-2 lg:order-1 z-20 mt-0 md:mt-14">
                            <SkeletonTwo
                                img1={one_png}
                                img2={two_png}
                                img3={three_png}
                            />
                        </div>
                        <div className="w-full lg:w-2/3 space-y-6 order-1 lg:order-2">
                            <div className="w-fit relative">
                                <h1 className="text-2xl md:text-4xl lg:text-6xl font-semibold text-white mb-4">
                                    Sathyabama
                                </h1>
                                <div className="absolute inset-x-20 bottom-0 left-0 bg-gradient-to-r from-transparent via-emerald-500 to-transparent h-[2px] w-3/4 blur-sm"/>
                                <div className="absolute inset-x-20 bottom-0 left-0 bg-gradient-to-r from-transparent via-emerald-500 to-transparent h-px w-3/4"/>
                                <div className="absolute inset-x-60 bottom-0 left-0 bg-gradient-to-r from-transparent via-rose-500 to-transparent h-[5px] w-1/4 blur-sm"/>
                                <div className="absolute inset-x-60 bottom-0 left-0 bg-gradient-to-r from-transparent via-rose-500 to-transparent h-px w-1/4"/>
                            </div>
                            <p className="text-lg lg:text-xl text-gray-300 leading-relaxed">
                                Sathyabama Institute of Science and Technology (SIST), formerly Sathyabama University,
                                is a private, STEM-intensive, multi-disciplinary deemed university in Chennai, Tamil Nadu, India.
                                Established in 1987, it is accredited with A++ grade by the National Assessment and Accreditation
                                Council (NAAC) and Category 1 University by the University Grants Commission (UGC),
                                the highest ratings by both boards. It is also an ISO 9001:2008 certified institution,
                                and has the distinction of being one of the very few universities in India to have successfully
                                built and launched its own space satellite, in association with ISRO.
                            </p>
                        </div>
                    </div>
                </div>
                <div id={"importantDates"} className={"pt-10"}>
                    <DateComponent />
                </div>
            </TracingBeam>
            <BackgroundBeams/>
        </div>
    );
}